### ISSUE TITLE
Есть предложение по комбо

### ISSUE THREAD

**Issue by kyt3** [KOTBCTAKAHE/hamster-kombo-server#1]
Даже не знал до сегодня, что комбо руками обновляется. Может сможешь сделать привязку... Например, можно привязаться хотя бы на месяц сюда 
https://www.cybersport.ru/tags/games/kombo-karty-v-hamster-kombat-khomiak-na-4-5-avgusta-2024-goda

Менять только дни, слать гет запрос. После, насколько я понял в html через js найти все списки https://ru.stackoverflow.com/questions/643882/%D0%9A%D0%B0%D0%BA-%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-%D0%B2%D1%81%D0%B5-li-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5-%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82-ul

Ну и пробегаться, искать совпадение по этим картам, чтобы по имени найти совпадения, а по ним id... И дальше 1 раз в день запускать. Я просто с JS вообще не знаком. Думаю, багов кучу наделаю. Если сделаешь - тебе менее хлопотно будет просто)

**Comment by KOTBCTAKAHE** [comment]
Здравствуйте! Благодарю вас за предложение! Конечно, я сделаю скрипт. Спасибо.

**Comment by KOTBCTAKAHE** [comment]
Дааа, это работает

**Comment by kyt3** [comment]
Давай тут, логичнее просто)) Просто по-разному карты называются для английской и русской локализации. "Finals are approaching" вместо "Игры, изменившие все". Если карты в репозитории нужны только для поиска - надо таскать имена с русской локализации и должно быть ок.

**Comment by KOTBCTAKAHE** [comment]
Блин, я не заметил, то что там на русском
