### ISSUE TITLE
Неверное комбо на сегодня.

### ISSUE THREAD

**Issue by kyt3** [KOTBCTAKAHE/hamster-kombo-server#4]
Сегодня неверное комбо в апи. Margin trading x10 вместо x50. Надо проверять почему если уже автоматом делается. Не вижу кода, даже предположить не могу как так?)

**Comment by KOTBCTAKAHE** [comment]
Здравствуй, я исправил

**Comment by KOTBCTAKAHE** [comment]
Автоматизацию я сделал на пайтон. И не через сайт "cybersport.ru" а со стороннего апи, сейчас дорабатываю, альтернативный источник, cybersport.ru. на python легче.

**Comment by kyt3** [comment]
Виновник источник? Бывает тогда, спасибо.
